### ISSUE TITLE
Got error when running example 

### ISSUE THREAD

**Issue by Bing1002** [lucidrains/transfusion-pytorch#12]
![Screenshot 2024-09-13 at 10 01 32](https://github.com/user-attachments/assets/ec664986-5f34-43f0-b584-1e789ee8b553)

**Comment by lucidrains** [comment]
hey Bing, the repo is not finished yet, but what version are you on? is this just the first readme example?

**Comment by Bing1002** [comment]
Hey Phil, I appreciate your implementation of this model and your quick response. I used the latest master branch and readme example.

**Comment by lucidrains** [comment]
@Bing1002 Motorola has an ML/AI research group? that's news to me!

**Comment by Bing1002** [comment]
> @Bing1002 Motorola has an ML/AI research group? that's news to me!



> @Bing1002 ah ok, can you try the updated readme?
> 
> i'm in the process of allowing the language model to dictate the shape of the modality
It works okay now. Thank you so much. It would be great if you are willing to add more comments on the model fake input saying which tensor is what?

**Comment by lucidrains** [comment]
@Bing1002 yea, i'll work my way towards the data end once the architecture is complete

for now, it is quite simple, any `torch.int` or `torch.long` is text, `torch.float` are modalities
