### ISSUE TITLE
Offset setting miss due to addition of meta_id and modality_meta_info?

### ISSUE THREAD

**Issue by jpwstu** [lucidrains/transfusion-pytorch#16]
In the loop `for modality in batch_modalities:`, the following tensor concatenation and offset setting is performed:

```
text_tensor = torch.cat((
    tensor_([self.meta_id]), # Flag indicating that the next token represents the shape
    modality_meta_info, # Shape token 4->313, 6->315
    tensor_([som_id]), # Start of modality token
    text_tensor, # Modality token (filled with -1)
    tensor_([eom_id]) # End of modality token
))
...
offset += modality_length + 2 # +2 due to [som] and [eom]
```

The addition of self.meta_id and modality_meta_info should cause the offset to shift by an additional 2 positions. However, the current implementation only considers som and eom tokens when setting the offset.

Thank you for your amazing work on this project!!!

**Comment by lucidrains** [comment]
@jpwstu oh gosh, thank you Shinichi! 🙏
