### ISSUE TITLE
[BUG] Fail to run the test samples

### ISSUE THREAD

**Issue by Masaaki-75** [lucidrains/transfusion-pytorch#17]
Thanks for the insightful implementation!

I was trying to run the test functions in https://github.com/lucidrains/transfusion-pytorch/blob/main/tests/test_transfusion.py, but got an error that came from the default arguments of `einops.reduce`, as shown below:
```
File "xxxx", line 647, in forward
    is_any_modality = reduce(is_modalities, 'b t m n -> b n', 'any')
  File "/opt/conda/envs/mllm/lib/python3.10/site-packages/einops/einops.py", line 420, in reduce
    raise EinopsError(message + '\n {}'.format(e))
einops.EinopsError:  Error while processing any-reduction pattern "b t m n -> b n".
 Input tensor shape: torch.Size([2, 1, 2, 150]). Additional info: {}.
 Unknown reduction any. Expect one of ('min', 'max', 'sum', 'mean', 'prod').
```

Just wondering if there's a plan for a stable test script? Thank you!

BTW, I found a possible bug in https://github.com/lucidrains/transfusion-pytorch/blob/main/tests/test_transfusion.py#L158, where it seems that the value assigned to `modality_default_shape` should be `((4,4),)` rather than `((4,4))` (current version doesn't make it a tuple of tuple and will throw an assertion error for being inconsistent with `self.num_modalities`).

**Comment by lucidrains** [comment]
hi Masaaki (who owns an RTX 4090)

you need to upgrade to the latest einops, so run `pip install einops -U`

**Comment by lucidrains** [comment]
@Masaaki-75 it should be taken care of [here](https://github.com/lucidrains/transfusion-pytorch/blob/main/transfusion_pytorch/transfusion.py#L972)

**Comment by Masaaki-75** [comment]
I see🫡 Thank you for the prompt reply!

**Comment by lucidrains** [comment]
@Masaaki-75 good luck with training!
