### ISSUE TITLE
Example of using VAE for image. 

### ISSUE THREAD

**Issue by dingkwang** [lucidrains/transfusion-pytorch#20]
Does anyone succeed to use vae for the image encoder/decoder? How to set it up?

```
vae = AutoencoderKL.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    subfolder="vae",
)
```

```
model = Transfusion(
    num_text_tokens = 1,
    dim_latent = 384,
    channel_first_latent = True,
    modality_default_shape = (4, 4),
    modality_encoder = vae.encoder,
    modality_decoder = vae.decoder,
    transformer = dict(
        dim = 512,
        depth = 8
    )
)
```

**Comment by lucidrains** [comment]
@dingkwang i'll work on a simplified autoencoder training wrapper over at [vq-pytorch](https://github.com/lucidrains/vector-quantize-pytorch), then allow for easy integration here

let's keep this open until i finish that (and as a reminder)

**Comment by lucidrains** [comment]
@dingkwang hey Dingkang

do you want to read [this](https://github.com/lucidrains/transfusion-pytorch/commit/17cda24c9c80435926074138281d282df42f5939) and see if it is self-explanatory? i'll embark on that autoencoder wrapper this week as well

**Comment by lucidrains** [comment]
@dingkwang think it is working given https://github.com/lucidrains/transfusion-pytorch/issues/22
