### ISSUE TITLE
Unsure of the functionality of one line

### ISSUE THREAD

**Issue by Ivan-Zhong** [lucidrains/transfusion-pytorch#28]
Hi, thank you very much for this work!

When I read through the code, I find that I am unsure of the functionality of the following line.
https://github.com/lucidrains/transfusion-pytorch/blob/d8523f131ce9193b7e950016d999bb0fbe39d559/transfusion_pytorch/transfusion.py#L1050

It seems that in the first transformer layer, `value_residual` will be updated to `attn_values`, and then for the following layers it will stay the same since it is not `None`. I wonder is this the expected behaviour? By the way, how would using `value_residual` help with transformer learning? Thanks a lot.

**Comment by lucidrains** [comment]
@Ivan-Zhong hey Yifan, thank you for your interest

yes that is the intended behavior, as the value residual comes from the first attention layer. the paper in question [is here](https://arxiv.org/abs/2410.17897), and is cited at the end of the readme
