### ISSUE TITLE
Memory access fault by GPU node-4 (Agent handle: 0x555556a31840) on address 0x7ff3c85d8000. Reason: Unknown.

### ISSUE THREAD

**Issue by mijanur132** [lucidrains/transfusion-pytorch#31]
This issue arise from value of this parameter:

  "  model = Transfusion(
        num_text_tokens = 10840,......."

My current experimental understanding is: It expects a value larger than the largest token value in my dataset. So if my dataset has largest token value 20845, If I give value lower than this like 20840- this will generate the memory access fault error. 

What this parameter requires? I thought it is the maximum sequence length the model can process like 512, 1024 or 2048. But putting these values gives the error. It works if I put value larger than the maximum token value which is very high like 50k or something. 

Can you kindly clarify which one is the case?

**Comment by lucidrains** [comment]
@mijanur132 hey, hope your research is going well

> My current experimental understanding is: It expects a value larger than the largest token value in my dataset.

this is correct, it corresponds to the number of unique text / discrete tokens in your dataset

there is no maximum sequence length, as transfusion works off relative positions with rotary embeddings

**Comment by lucidrains** [comment]
@mijanur132 in other words, you need to set `num_text_tokens = 20846`

**Comment by mijanur132** [comment]
Thanks for your prompt response. Appreciate it.
