### ISSUE TITLE
LlamaFusion paper

### ISSUE THREAD

**Issue by RefractAI** [lucidrains/transfusion-pytorch#32]
https://arxiv.org/pdf/2412.15188

Follow-up paper to Transfusion by Meta ("LlamaFusion")

Makes the following modifications to Transfusion for significantly increased performance
- Separate image and text QKV projection, FFN and norm
- Use either image or text layers depending on current modality. Self attention is over both.
- Use a pretrained LLM for the text layers and freeze it, retaining existing text capability

**Comment by lucidrains** [comment]
@RefractAI nice, yea none of those are surprising

Robin Rombach totally called this as usual. that man is light years ahead
