### ISSUE TITLE
Implementation of Conditional Injection in Transfusion Differs from Original Paper

### ISSUE THREAD

**Issue by lavinal712** [lucidrains/transfusion-pytorch#34]
I have observed that the implementation of conditional injection in the "transfusion" module differs from what is described in the original paper. Specifically, your code utilizes the `adaln_zero` method for conditional injection, whereas the paper states: "We add an embedding of the timestep t to every patch vector before the linear layer."

**Comment by lucidrains** [comment]
@lavinal712 ah, yes that could work too

think it makes little difference, the ada-ln zero conditioning may be even better
