### ISSUE TITLE
Question about num_text_tokens setting in Transfusion

### ISSUE THREAD

**Issue by wdlctc** [lucidrains/transfusion-pytorch#4]
Hi,

I’m working with the Transfusion model and I came across a code snippet in the paper that mentions the following configuration:
```

model = Transfusion(
    num_text_tokens = 16384,
    transformer = dict(
        dim = 768,
        depth = 16
    )
)

text_ids = torch.randint(0, 256, (1, 4096)).cuda()
```

I wanted to confirm if the num_text_tokens setting in this snippet is indeed set to 16384, as indicated in the paper. Is this the correct setting, or should it be different?

Thanks in advance for your clarification!

Best regards,
cheng

**Comment by Carolinabanana** [comment]
num_text_tokens is the embedding size i.e. tokenizer vocab size. That code does not appear in the linked paper at all.

**Comment by wdlctc** [comment]
Thank you for a quick reply, I was wondering, on paper page 8 it mentions that 

> We use a codebook of 16,384 token types.

Is it the value of tokenizer vocab size

**Comment by Carolinabanana** [comment]
> Thank you for a quick reply, I was wondering, on paper page 8 it mentions that
> 
> > We use a codebook of 16,384 token types.
> 
> Is it the value of tokenizer vocab size

That is specifically for when they train a VQVAE for Chameleon, as a comparison/evaulation. The Transfusion architecture itself uses a VAE, not a VQVAE, so it does not have a codebook.

**Comment by wdlctc** [comment]
I got it; many thanks!
