### ISSUE TITLE
Question about Diffusion Loss

### ISSUE THREAD

**Issue by JJJYmmm** [lucidrains/transfusion-pytorch#8]
https://github.com/lucidrains/transfusion-pytorch/blob/e452ca10b64e98b5a2510b2eea4bfc29ff0938d8/transfusion_pytorch/transfusion.py#L741-L756

Why the diffusion objective `flows` is `data - noise` rather than `data` ?

**Comment by lucidrains** [comment]
@JJJYmmm i actually went for flow matching first

think given Robin Rombach's amazing work with flux, it is a proven approach
